# Generated by Django 5.1.2 on 2024-11-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails4you', '0005_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Termin',
        ),
    ]
