# Generated by Django 5.1.2 on 2024-11-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails4you', '0006_delete_termin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
